---
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    container_name: mealie-frontend
    restart: always
    environment:
      # Set Frontend ENV Variables Here
      - API_URL=http://mealie-api:9000
    ports:
      - "9001:3000"
    volumes:
      - mealie-data:/app/data/

  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    container_name: mealie-api
    restart: always
    volumes:
      - mealie-data:/app/data/
    env_file:
      - ../shared.env
    environment:
      # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=http://home.neil.gg:9001
      - SMTP_FROM_EMAIL=mealie@neil.gg

volumes:
  mealie-data:
    driver: local
