version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "2021:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
    labels:
      - docker-volume-backup.stop-during-backup=true
    environment:
      - PAPERLESS_REDIS=redis://broker:6379
      - PAPERLESS_TIME_ZONE=America/Chicago
      # Set if accessing paperless via a domain subpath e.g. https://domain.com/PATHPREFIX and using a reverse-proxy like traefik or nginx
      # - PAPERLESS_FORCE_SCRIPT_NAME=/PATHPREFIX
      # - PAPERLESS_STATIC_URL=/PATHPREFIX/static/ # trailing slash required

  backup:
    image: offen/docker-volume-backup:latest
    restart: always
    env_file:
      - ../backup.env
    environment:
      - AWS_S3_PATH=paperless
      - BACKUP_FILENAME=paperless-%Y-%m-%dT%H-%M-%S.tar.gz
      - BACKUP_PRUNING_PREFIX=paperless-
      - BACKUP_RETENTION_DAYS=7
    volumes:
      - data:/backup/data:ro
      - media:/backup/media:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  data:
  media:
  redisdata:
