version: "3.4"
services:
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    restart: unless-stopped
    ports:
      - '9000:9000'
    environment:
      - ASR_ENGINE=faster_whisper
      - ASR_MODEL=medium.en
