version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    labels:
      - docker-volume-backup.stop-during-backup=true
 
  backup:
    image: offen/docker-volume-backup:latest
    restart: always
    env_file:
      - ../backup.env
    environment:
      - AWS_S3_PATH=nginx_proxy_manager
    volumes:
      - data:/backup/data:ro
      - letsencrypt:/backup/letsencrypt:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  data:
  letsencrypt:
